--- 
title: "Data Science at the Command Line Book Club"
author: "The R4DS Online Learning Community"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
github-repo: r4ds/bookclub-dscl
description: "This is the product of the R4DS Online Learning Community's Data Science at the Command Line Book Club."
---

# Welcome {-}

Welcome to the bookclub! 

This is a companion for the book [_Data Science at the Command Line_](https://datascienceatthecommandline.com/2e/) by Jeroen Janssens ( O’Reilly Media, copyright October 2021, [978-1492087915](https://www.oreilly.com/library/view/data-science-at/9781492087908/)).
This companion is available at [r4ds.io/dscl](https://r4ds.io/dscl).

This website is being developed by the [R4DS Online Learning Community](https://rfordatasci.com). Follow along, and [join the community](https://r4ds.io/join) to participate.

This companion follows the [R4DS Online Learning Community Code of Conduct](https://r4ds.io/conduct).

## Book club meetings {-}

- Each week, a volunteer will present a chapter from the book (or part of a chapter).
  - **This is the best way to learn the material.**
- Presentations will usually consist of a review of the material, a discussion, and/or a demonstration of the principles presented in that chapter.
- More information about how to present is available in the [github repo](https://github.com/r4ds/bookclub-dscl).
- Presentations will be recorded, and will be available on the [R4DS Online Learning Community YouTube Channel](https://r4ds.io/youtube).

## Pace {-}

- We'll _try_ to cover 1 chapter/week, but...
- ...It's ok to split chapters when they feel like too much.
- We will try to meet every week, but will likely take some breaks for holidays, etc.
